Repository wilhelm-lab/spectrum_fundamentals, pull requests merged in 2024-07, with the labels that each got.

#114 fix lda_failed and stablized RT alignment
  noxfile.py
  poetry.lock
  spectrum_fundamentals/metrics/percolator.py
  tests/unit_tests/test_percolator.py
Labels: bug

#103 Added PROTEINS column to meta data
  .cookietemple.yml
  .github/release-drafter.yml
  cookietemple.cfg
  docs/conf.py
  pyproject.toml
  spectrum_fundamentals/__init__.py
  spectrum_fundamentals/__main__.py
  spectrum_fundamentals/constants.py
Labels: enhancement

#120 Feature/custom modifications
  spectrum_fundamentals/annotation/annotation.py
  spectrum_fundamentals/constants.py
  spectrum_fundamentals/fragments.py
  spectrum_fundamentals/mod_string.py
  tests/unit_tests/test_constants.py
  tests/unit_tests/test_mod_string.py
Labels: enhancement

#122 use custom columns as input features for percolator
  spectrum_fundamentals/metrics/percolator.py
  tests/unit_tests/test_percolator.py
Labels: enhancement

#126 changed order of iontypes in preprocessing
  spectrum_fundamentals/fragments.py
  tests/unit_tests/test_fragments.py
Labels: enhancement

#69 Feature/documentation
  README.rst
  ReadMe.md
  docs/API.rst
  docs/_key_contributors.rst
  docs/_static/custom_cookietemple.css
  docs/authors.rst
  docs/code_of_conduct.rst
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  docs/installation.rst
  docs/modules.rst
  docs/news.rst
  docs/quickstart.rst
  docs/reference.rst
  docs/requirements.txt
  docs/spectrum_fundamentals.annotation.rst
  docs/spectrum_fundamentals.metrics.rst
  docs/spectrum_fundamentals.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  requirements.txt
  spectrum_fundamentals/__init__.py
Labels: enhancement, chore
